<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>testing</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MarkdownSnippets.MsBuild" PrivateAssets="all" />
    <PackageReference Include="Verify" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="Argon" />
    <PackageReference Include="DiffEngine" />
    <PackageReference Include="EmptyFiles" />
    <PackageReference Include="SimpleInfoName" />
    <ProjectReference Include="..\Verify.Yaml\Verify.Yaml.csproj" />
  </ItemGroup>
</Project>
